"""Source-data models for LoanLens.

The models intentionally contain user-entered facts only. Calculated balances,
interest allocations, and payoff estimates are generated by ``engine.py``.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date


@dataclass(frozen=True, slots=True)
class RateChange:
    """An annual interest rate effective from a calendar date."""

    effective_date: date
    annual_rate: float

    def __post_init__(self) -> None:
        if not 0 <= self.annual_rate <= 100:
            raise ValueError("Annual interest rate must be between 0 and 100 percent.")


@dataclass(frozen=True, slots=True)
class Payment:
    """A payment event.

    ``credited_date`` wins when supplied because lenders usually calculate from
    the posting/credit date. Otherwise, LoanLens uses ``payment_date`` and
    makes that assumption visible in the UI.
    """

    payment_id: str
    amount: float
    payment_date: date
    credited_date: date | None = None
    payment_type: str = "EMI"
    source: str = "recorded"

    def __post_init__(self) -> None:
        if self.amount <= 0:
            raise ValueError("Payment amount must be greater than zero.")
        if self.credited_date and self.credited_date < self.payment_date:
            raise ValueError("Credited date cannot be before the payment date.")
        if self.source not in {"recorded", "modeled"}:
            raise ValueError("Payment source must be 'recorded' or 'modeled'.")

    @property
    def effective_date(self) -> date:
        """Return the date on which the payment affects the balance."""

        return self.credited_date or self.payment_date


@dataclass(frozen=True, slots=True)
class LoanConfig:
    """Loan setup and projection assumptions."""

    original_amount: float
    disbursement_date: date
    current_outstanding: float
    outstanding_as_of: date
    current_annual_rate: float
    current_emi: float
    emi_start_date: date
    emi_day: int
    tenure_months: int
    moratorium_months: int = 0
    grace_months: int = 0
    part_interest_amount: float = 0.0
    model_part_interest: bool = False
    day_count_basis: int = 365

    def __post_init__(self) -> None:
        if self.original_amount <= 0:
            raise ValueError("Original amount must be greater than zero.")
        if self.current_outstanding < 0:
            raise ValueError("Current outstanding cannot be negative.")
        if not 0 <= self.current_annual_rate <= 100:
            raise ValueError("Current interest rate must be between 0 and 100 percent.")
        if self.current_emi < 0:
            raise ValueError("Current EMI cannot be negative.")
        if not 1 <= self.emi_day <= 28:
            raise ValueError("EMI day must be between 1 and 28.")
        if self.tenure_months <= 0:
            raise ValueError("Tenure must be greater than zero months.")
        if self.moratorium_months < 0 or self.grace_months < 0:
            raise ValueError("Moratorium and grace periods cannot be negative.")
        if self.part_interest_amount < 0:
            raise ValueError("Part-interest amount cannot be negative.")
        if self.day_count_basis not in {360, 365, 366}:
            raise ValueError("Day-count basis must be 360, 365, or 366.")
        if self.outstanding_as_of < self.disbursement_date:
            raise ValueError("Current balance date cannot be before disbursement.")
